#!/bin/sh
### BEGIN INIT INFO
# Provides:             xtendpid
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6 
# Short-Description:    linux daemon to access i/o on pixtend board
# Description:          linux daemon to access i/o on pixtend board
### END INIT INFO

# Actions
case "$1" in
  start)
    xtendpid
    ;;
  stop)
    pkill xtendpid
    ;;
  restart)
    pkill xtemdpid
    xtendpid
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac

exit 0
