#!/bin/sh
### BEGIN INIT INFO
# Provides:             xtendpid
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6 
# Short-Description:    linux daemon to access i/o on pixtend board
# Description:          linux daemon to access i/o on pixtend board
### END INIT INFO

# Actions
case "$1" in
  start)
    echo 24 > /sys/class/gpio/unexport
    echo 23 > /sys/class/gpio/unexport

    echo 24 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio24/direction
    echo 1 > /sys/class/gpio/gpio24/value

    echo 23 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio23/direction
    echo 1 > /sys/class/gpio/gpio23/value
    echo 0 > /sys/class/gpio/gpio23/value

    sleep 1

    xtendpid
    ;;
  stop)
    pkill xtendpid

    echo 24 > /sys/class/gpio/unexport
    echo 23 > /sys/class/gpio/unexport
    ;;
  restart)
    pkill xtendpid

    echo 24 > /sys/class/gpio/unexport
    echo 23 > /sys/class/gpio/unexport

    echo 24 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio24/direction
    echo 1 > /sys/class/gpio/gpio24/value

    echo 23 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio23/direction
    echo 1 > /sys/class/gpio/gpio23/value
    echo 0 > /sys/class/gpio/gpio23/value

    sleep 1

    xtendpid
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac

exit 0
